import Head from 'next/head'
import Hero from '../components/Hero'
import Nav from '../components/Nav'
import Portfolio from '../components/Portfolio'
import Services from '../components/Services'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import { createClient } from "next-sanity"
import { Toaster } from 'react-hot-toast'

export default function Home({works}) {
  console.log(works)
  return (
    <div className="bg-gray-900">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster />
      <Nav />
      <Hero />
      <Services />
      <Portfolio works={works} />
      <Contact />
      <Footer />
    </div>
  )
}

export async function getServerSideProps() {
  const client = createClient({
    projectId:process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
    dataset:"production",
    useCdn:false
  })
  const query = `*[_type == 'post']`
  const works = await client.fetch(query)
  return { 
    props: { 
      works
    }
  }
}
